name: manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  video_player:
  connectivity_plus: ^6.1.4
  internet_connection_checker_plus: ^2.7.2
  firebase_storage:
  image_picker:
  cloud_firestore:
  firebase_core:
  firebase_database:
  file_picker:

  cupertino_icons: ^1.0.8
  image_cropper: ^9.1.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1
  flutter_image_compress: ^2.4.0
  easy_localization: ^3.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
