// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB654a-o23AohCCS5d-XVSHimMh97Fwdog',
    appId: '1:614133323638:web:ac9a81f6ad5d2934f60c57',
    messagingSenderId: '614133323638',
    projectId: 'smartads-49711',
    authDomain: 'smartads-49711.firebaseapp.com',
    storageBucket: 'smartads-49711.firebasestorage.app',
    measurementId: 'G-ZNZ36DXV2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjEumHuF13E2SwzzfpWAtSmzjJFC7af0o',
    appId: '1:614133323638:android:cee8fc87b375c7f4f60c57',
    messagingSenderId: '614133323638',
    projectId: 'smartads-49711',
    storageBucket: 'smartads-49711.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUr3qnt3IMo3H7s9GWJaVoYQ8lP9MZUN4',
    appId: '1:614133323638:ios:16267c2ba807c6e1f60c57',
    messagingSenderId: '614133323638',
    projectId: 'smartads-49711',
    storageBucket: 'smartads-49711.firebasestorage.app',
    iosBundleId: 'com.example.khaledAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUr3qnt3IMo3H7s9GWJaVoYQ8lP9MZUN4',
    appId: '1:614133323638:ios:16267c2ba807c6e1f60c57',
    messagingSenderId: '614133323638',
    projectId: 'smartads-49711',
    storageBucket: 'smartads-49711.firebasestorage.app',
    iosBundleId: 'com.example.khaledAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB654a-o23AohCCS5d-XVSHimMh97Fwdog',
    appId: '1:614133323638:web:2f9a2895b0883c17f60c57',
    messagingSenderId: '614133323638',
    projectId: 'smartads-49711',
    authDomain: 'smartads-49711.firebaseapp.com',
    storageBucket: 'smartads-49711.firebasestorage.app',
    measurementId: 'G-XM04LGE6K2',
  );
}
